[INFORMATION]
[TITLE]2
[AUTHOR]
[SOURCE]
[PRG]
[FILEPATH]
[DELAY]0
[CD TRACK]0
[COMMENT]
[END INFORMATION]
[SUBTITLE]
[COLF]&H000000,[STYLE]bd,[SIZE]25,[FONT]Arial
00:00:00.64,00:00:04.66
China and Japan are two countries that have[br]been culturally intertwined from as early

00:00:04.66,00:00:06.58
as 400 AD.

00:00:06.58,00:00:10.75
This relationship led to Japan adopting the[br]Chinese writing system, the religion of Buddhism,

00:00:10.75,00:00:15.96
similar political systems, as well as developing[br]in matters of food, fashion, law, and more,

00:00:15.96,00:00:17.61
under the influence of China.

00:00:17.61,00:00:20.79
Although the countries are currently at peace,[br]relations have remained somewhat tense over

00:00:20.79,00:00:21.80
the last century.

00:00:21.80,00:00:25.57
Today, we’ll compare the two nations in[br]a hypothetical military match-up, in this

00:00:25.57,00:00:28.56
episode of The Infographics Show, China vs.[br]Japan.

00:00:28.56,00:00:31.46
Don’t forget to subscribe and click the[br]bell button so that you can be part of our

00:00:31.46,00:00:32.80
Notification Squad.

00:00:32.80,00:00:37.69
The USA has the world’s highest GDP of around[br]18.5 trillion dollars.

00:00:37.69,00:00:42.93
It’s followed by China with a nominal GDP[br]of 11.8 trillion dollars, and then Japan with

00:00:42.93,00:00:45.85
a GDP of around 4.8 trillion dollars.

00:00:45.85,00:00:50.49
The European Union would take second place,[br]but the EU is a combination of 28 states.

00:00:50.49,00:00:55.36
While China has experienced economic prosperity[br]in recent years, it’s per capita GDP ranks

00:00:55.36,00:01:01.82
low, globally in 70th place, at around 8,000[br]dollars, with Japan’s per capita GDP much

00:01:01.82,00:01:04.39
higher at around 39,000 dollars.

00:01:04.39,00:01:08.49
There is certainly less money to go around[br]in China as it has the world’s largest population

00:01:08.49,00:01:15.06
of 1.38 billion people, compared to Japan’s[br]126-plus million population.

00:01:15.06,00:01:19.56
In terms of military spending, China ranks[br]third behind Russia and the military-minded

00:01:19.56,00:01:26.18
USA, with a defense budget of around $147[br]billion, which is 2.1% of its GDP.

00:01:26.18,00:01:31.52
Japan sits in 7th place on this list, with[br]a $43 billion defense budget, which is 0.9%

00:01:31.52,00:01:32.74
of its GDP.

00:01:32.74,00:01:37.36
It’s also worth mentioning here that military[br]pundits often state China spends much more

00:01:37.36,00:01:41.62
on its military than the number that is reported,[br]although China’s finance minister denied

00:01:41.62,00:01:47.07
this secrecy in 2017, saying, “Let me be[br]very clear, there is no such thing as opacity

00:01:47.07,00:01:48.98
in China’s military spending.”

00:01:48.98,00:01:52.76
While Japan is regarded as being a military[br]powerhouse, it’s number of military personnel

00:01:52.76,00:01:57.81
is actually quite small, and very much inferior[br]to the number of personnel the Chinese employ.

00:01:57.81,00:02:04.47
Japan has around 250,000 active military personnel,[br]with another 57,900 people acting as reserve

00:02:04.47,00:02:05.49
personnel.

00:02:05.49,00:02:12.64
China on the other hand has a massive 2,335,000[br]active frontline personnel and 2,300,000 active

00:02:12.64,00:02:15.48
reserve personnel and paramilitary forces.

00:02:15.48,00:02:19.15
Japan’s personnel numbers may be small,[br]but it's protected with some of the world’s

00:02:19.15,00:02:20.65
best military equipment.

00:02:20.65,00:02:28.44
This includes 678 Tanks, 2,850 armored fighting[br]vehicles, 202 self-propelled guns, 500 Towed-Artillery,

00:02:28.44,00:02:30.57
and 99 multiple launch rocket systems.

00:02:30.57,00:02:35.15
It’s large fleet of land artillery includes[br]two machines often on the list of the world’s

00:02:35.15,00:02:40.51
most advanced tanks, those being the Japanese-made[br]Type 10 Main Battle Tank and Type 90 Main

00:02:40.51,00:02:41.51
Battle Tank.

00:02:41.51,00:02:51.14
China, however, outguns Japan considerably[br]with a total of 9,150 tanks, 4,788 AFVs, 1,710

00:02:51.14,00:02:55.93
SPGs, 6,246 Towed-Artillery, and 177 MLRSs.

00:02:55.93,00:03:00.95
China’s Type 99 main battle tank is also[br]highly rated, while the country also claims

00:03:00.95,00:03:04.78
to have developed the most advanced tank in[br]the world in its VT-4.

00:03:04.78,00:03:09.17
China is not alone in making such boastful[br]claims, with the USA and Russia also stating

00:03:09.17,00:03:14.63
they have the best tanks in the M1A2 Abrams[br]and the T-14 Armata, respectively.

00:03:14.63,00:03:19.08
The VT-4 is as much a Chinese war machine[br]as it is a profitable export, with Thailand

00:03:19.08,00:03:23.53
placing a big order of the tanks, and other[br]countries showing interest in buying.

00:03:23.53,00:03:28.38
Both countries have strong air forces, with[br]China owning around 2,900-plus aircraft and

00:03:28.38,00:03:30.44
206 attack helicopters.

00:03:30.44,00:03:35.60
Japan has around 1,590 aircraft and 119 attack[br]helicopters.

00:03:35.60,00:03:41.24
In terms of strength, China’s aerial piece[br]de resistance is its new Chengdu J-20 stealth

00:03:41.24,00:03:46.11
fighter, which the air force, and some aviation[br]experts, have stated can match America’s

00:03:46.11,00:03:50.45
highly advanced Lockheed Martin F-22 Raptor[br]and F-35.

00:03:50.45,00:03:54.65
China is also the only country to have bought[br]the Russian beasts of the skies, the Sukhoi

00:03:54.65,00:03:56.71
Su-35 multipurpose fighter.

00:03:56.71,00:04:01.20
If you’ve seen our shows on these aircraft,[br]you’ll know the Su-35 alone is an impeccable

00:04:01.20,00:04:02.82
piece of engineering.

00:04:02.82,00:04:07.20
Japan would be hard pushed to equal such aerial[br]military might, but the country is no slouch

00:04:07.20,00:04:08.59
when it comes to aircraft.

00:04:08.59,00:04:12.86
Japan is said to have created a veritable[br]equal to China’s J-20, having joined the

00:04:12.86,00:04:15.61
stealth leagues with its own Mitsubishi X-2.

00:04:15.61,00:04:20.64
Japan has some formidable combat aircraft[br]in its homemade Mitsubishi F-2, as well as

00:04:20.64,00:04:24.56
American made F-4 Phantom IIs and F-15 Eagles.

00:04:24.56,00:04:29.14
The country is also the proud owner of the[br]USA’s highly touted F-35 Lightning II.

00:04:29.14,00:04:33.31
Japan currently has one of these aircraft,[br]but another 42 have been ordered.

00:04:33.31,00:04:36.80
With this in mind, the two countries seem[br]to be fairly evenly matched in terms of air

00:04:36.80,00:04:40.11
force equipment, with Japanese imports being[br]a major factor.

00:04:40.11,00:04:44.54
As far as naval power is concerned, a matter[br]of significance given the history of naval

00:04:44.54,00:04:48.11
invasions, and the fact that the countries[br]are separated by a stretch of water.

00:04:48.11,00:04:52.08
Both countries are credited with having very[br]strong navies, although most analysts rank

00:04:52.08,00:04:53.76
China above Japan.

00:04:53.76,00:04:58.54
The People’s Liberation Army Navy is said[br]to have grown from a fairly weak outfit consisting

00:04:58.54,00:05:03.80
of old ships to a formidable foe due to massive[br]injections of money since China’s economic

00:05:03.80,00:05:04.80
boom.

00:05:04.80,00:05:09.25
The navy not only has well over 100,000 personnel,[br]but has a large fleet of ships.

00:05:09.25,00:05:15.62
This includes one aircraft carrier, 35 destroyers,[br]51 frigates, 35 corvettes, 31 mine warfare,

00:05:15.62,00:05:21.41
3 amphibious transports, 8 nuclear attack[br]submarines, and around 50 conventional attack

00:05:21.41,00:05:22.41
submarines.

00:05:22.41,00:05:28.37
By comparison, the Japanese navy consists[br]of around 114 ships and 45,800 personnel,

00:05:28.37,00:05:33.47
and according to nationalinterest.org, its[br]fleet of 17 submarines is as good as any submarine

00:05:33.47,00:05:34.47
fleet in the world.

00:05:34.47,00:05:40.35
In total, Japan has 3 Aircraft Carriers, 43[br]Destroyers, 6 Coastal Defense Craft, 0 Frigates,

00:05:40.35,00:05:43.00
0 Corvettes, and 25 mine warfare.

00:05:43.00,00:05:45.83
A matter of importance is each country’s[br]nuclear capabilities.

00:05:45.83,00:05:49.75
Japan doesn’t have any nuclear weapons,[br]although it is protected by the United States

00:05:49.75,00:05:51.14
under the nuclear umbrella.

00:05:51.14,00:05:54.88
The country is well known for its highly advanced[br]industries and technology, and there is no

00:05:54.88,00:05:59.32
doubt that it could develop its own nuclear[br]weapons given its nuclear energy infrastructure.

00:05:59.32,00:06:03.75
This has so far not happened due to a non-nuclear[br]weapons policy, although being positioned

00:06:03.75,00:06:08.46
so close to North Korea, many Japanese politicians[br]and military officials have called for a change

00:06:08.46,00:06:09.99
in nuclear weapons policy.

00:06:09.99,00:06:14.22
China, on the other hand, is one of 9 nations[br]with nuclear weapons, with a considerable

00:06:14.22,00:06:16.33
arsenal of around 260 warheads.

00:06:16.33,00:06:19.31
It’s first nuclear test was in 1964.

00:06:19.31,00:06:23.00
The number of weapons, however, and China’s[br]development of nuclear weapons, has been a

00:06:23.00,00:06:24.82
matter of wide speculation.

00:06:24.82,00:06:28.60
For instance, a Georgetown University study[br]claimed that China’s nuclear weapons arsenal

00:06:28.60,00:06:31.63
is not in the hundreds, but possibly 3,000.

00:06:31.63,00:06:34.76
The study claimed the weapons were hidden[br]in secret underground tunnels.

00:06:34.76,00:06:38.46
The prospect of any kind of conflict involving[br]these weapons of mass destruction, however,

00:06:38.46,00:06:40.18
is highly unlikely.

00:06:40.18,00:06:44.64
We cannot forget that almost every single[br]tank, aircraft, or naval unit needs fuel to

00:06:44.64,00:06:45.64
operate.

00:06:45.64,00:06:48.77
China currently consumes approximately 12[br]million (11,968,000) barrels of oil a day,

00:06:48.77,00:06:51.82
but it only produces about 4 million (3,980,000)[br]barrels daily.

00:06:51.82,00:06:55.21
That said, it does have 25 billion barrels[br]in reserves.

00:06:55.21,00:07:00.98
Japan, on the other hand, consumes 4.15 million[br]barrels of oil a day, but it only produces

00:07:00.98,00:07:03.89
a meager 3,900 barrels daily.

00:07:03.89,00:07:07.87
Worse yet, it only has 44 million barrels[br]of oil in reserves.

00:07:07.87,00:07:10.33
So, who do you think has a stronger military?

00:07:10.33,00:07:11.33
China or Japan?

00:07:11.33,00:07:12.73
Let us know why in the comments!

00:07:12.73,00:07:15.36
And be sure sure to check out our military[br]comparisons playlist.

00:07:15.36,00:07:18.16
Thanks for watching, and, as always, don’t[br]forget to like, share, and subscribe.

00:07:18.16,00:00:00.00
See you next time!